In [50]:
import numpy as np

In [51]:
arr = np.array([1,2,3,4,5])

In [52]:
print(arr)

[1 2 3 4 5]


In [53]:
print(np.__version__)

1.18.5


In [54]:
arr1 = np.array([[1,2,3,4,5],[6,7,8,9,10]]) # [[0] , [1]] array 2d

In [55]:
print(arr1[1,0])

6


In [56]:
arr2 = np.array([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
]) # [[0],[1] [2]] array 3d

In [57]:
print(arr2[0][2][0])

7


In [58]:
print(arr[1:5:2])# start:end:step

[2 4]


In [59]:
print(arr2[0,0:3])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [60]:
print(arr2.dtype)

int32


In [61]:
newarr2 = arr2.astype(float)
print(newarr2)
print(newarr2.dtype)

[[[1. 2. 3.]
  [4. 5. 6.]
  [7. 8. 9.]]]
float64


In [62]:
x = arr.copy()
arr[0] = 55
print(arr)
print(x)

[55  2  3  4  5]
[1 2 3 4 5]


In [63]:
y = arr.view()
arr[0] = 888
print(arr)
print(y)

[888   2   3   4   5]
[888   2   3   4   5]


In [64]:
arr3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr3 = arr3.reshape(4,3)
print(newarr3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [68]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [71]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
for idx,x in np.ndenumerate(arr):
    print(idx,x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(0, 4) 5
(1, 0) 6
(1, 1) 7
(1, 2) 8
(1, 3) 9
(1, 4) 10


In [72]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [74]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [75]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

(array([3, 5, 6], dtype=int64),)


In [77]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 0) #show number odd
print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [78]:
x = np.where(arr%2 == 1)#show number even

print(x)

(array([0, 2, 4, 6], dtype=int64),)


In [81]:
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr,7) #search in array
print(x)

0


In [80]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr)) # sort

[0 1 2 3]


In [82]:
arr = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr))

['apple' 'banana' 'cherry']


In [83]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [84]:
arr = np.array([41, 42, 43, 44])
filter_arr = []
for element in arr:
    if element >= 43:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [88]:
from numpy import random
x = random.randint(100)
print(x)

15
